server:
  port: 0
  
remoteserver:
    uri:
        register: /session/register
        logout: /session/logout
        challenge: /session/login/challenge
        authenticate: /session/login/authenticate
        documents:  /api/groups/{var0}/documents/{var1}
        friends:   /api/{preffix1}/friends/{suffix1}/{suffix2}/{suffix3}
        users:     /api/{prefix1}/{prefix2}/users/{suffix1}/{suffix2}
        groups:    /api/groups/{suffix1}/{suffix2}/{suffix3}/{suffix4}/
        keypairs:  /api/{userId}/keypair
        symkeys:   /api/{groupId}/keysym
        url: http://localhost:8080
        
cipher:
  symmetric:
    key_algo: AES
    cipher_algo: AES/ECB/PKCS7Padding
    keylenght: 128
  asymmetric:
    key_algo: RSA
    cipher_algo: RSA
    keylenght: 1024
  hash:
    algo: MD5
  salt:
    algo: SHA1PRNG
        