server:
  port: 0
  
  
remoteserver:
    uri:
        register: /session/register
        logout: /session/logout
        challenge: /session/login/challenge
        authenticate: /session/login/authenticate
        documents: /api/groups/{preffix}/documents/{suffix2}
        friends:   /api/{preffix1}/friends/{suffix1}/{suffix2}/{suffix3}
        users:     /api/{prefix1}/{prefix2}/users/{suffix1}/{suffix2}
        groups:    /api/groups/{suffix1}/{suffix2}/{suffix3}/{suffix4}/
        keypairs:  /api/{userId}/keypair
        symkeys:   /api/{groupId}/keysym
        url: http://localhost:8080
 
