uri:
    session:
        register: /session/register
        logout: /session/logout
        login:
            challenge: /session/login/challenge
            authenticate: /session/login/authenticate
